name: fraud-batch-inference-pipeline

on:
  workflow_dispatch:
#  schedule:
#    - cron: '11 11 * * *'

jobs:
  setup-versions-from-manifest:
    name: Setup ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04, ubuntu-20.04]
        python: [3.5.4, 3.6.7, 3.7.5, 3.8.1]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: setup-python ${{ matrix.python }}
      id: setup-python
      uses: ./
      with:
        python-version: ${{ matrix.python }}

    - name: Check python-path
      run: ./__tests__/check-python-path.sh '${{ steps.setup-python.outputs.python-path }}'
      shell: bash

    - name: Validate version
      run: |
        $pythonVersion = (python --version)
        if ("Python ${{ matrix.python }}" -ne "$pythonVersion"){
          Write-Host "The current version is $pythonVersion; expected version is ${{ matrix.python }}"
          exit 1
        }
        $pythonVersion
      shell: pwsh

    - name: Run simple code
      run: python -c 'import math; print(math.factorial(5))'


